Repository xperseguers/t3ext-oidc, pull requests merged in 2024-12, with the labels that each got.

#182 Prevents intExplode on null
  Classes/Service/AuthenticationService.php
Labels: feedback needed

#181 [TASK] Use v2.8 of league/oauth2-client
  Classes/Service/OAuthService.php
  composer.json
Labels: enhancement

#184 [FEATURE] Make TYPO3 v13 compatible
  Classes/Controller/LoginController.php
  Classes/Frontend/FrontendSimulationInterface.php
  Classes/Frontend/FrontendSimulationV11.php
  Classes/Frontend/FrontendSimulationV12.php
  Classes/Frontend/FrontendSimulationV13.php
  Classes/Service/AuthenticationService.php
  Classes/Service/OAuthService.php
  Classes/Service/OpenIdConnectService.php
  Configuration/TypoScript/setup.typoscript
  composer.json
  ext_emconf.php
  ext_localconf.php
Labels: enhancement

#186 [BUGFIX] Use explicitly passed request instead of global request
  Classes/Service/OAuthService.php
  Classes/Service/OpenIdConnectService.php
Labels: bug
